In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

In [11]:
print(np.linalg.eig.__doc__)


    Compute the eigenvalues and right eigenvectors of a square array.

    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed

    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs

    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.

    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not converge.

    See Also
    --------
    eigvals : eigenvalues of a non-sym

In [2]:
N = 5 # total population
Rsi = 1

I_0 = 1
S_0 = 4

d1 = np.asarray([i * (N - i) for i in reversed(range(S_0 + 1))])
d2 = np.asarray([0] + [i * (N - i) for i in reversed(range(1, S_0 + 1))])
A = (np.eye(S_0 + 1) * d1[:, np.newaxis]) - (np.eye(S_0 + 1, k=-1) * d2[:, np.newaxis])


In [3]:
A

array([[ 4.,  0.,  0.,  0.,  0.],
       [-4.,  6.,  0.,  0.,  0.],
       [ 0., -6.,  6.,  0.,  0.],
       [ 0.,  0., -6.,  4.,  0.],
       [ 0.,  0.,  0., -4.,  0.]])

In [4]:
w, v = np.linalg.eig(A)
v_inv = np.linalg.inv(v.copy())
w = np.diag(w.copy())

In [5]:
w

array([[0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 4.]])

In [6]:
v @ v_inv

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
v_inv

array([[-2.26935622e+00, -1.32238173e-01,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-5.73214651e+16, -5.61039052e-01,  4.24264069e+00,
         1.41421356e+00,  0.00000000e+00],
       [ 3.37018536e+16, -1.68509268e+16,  3.74165739e+00,
         0.00000000e+00,  0.00000000e+00],
       [-3.37018536e+16,  1.68509268e+16, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00],
       [ 5.73214651e+16,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [13]:
np.allclose(v_inv @ w @ v_inv, (v @ w) @ v_inv) # v * (w * v^(-1)) vs (v * w) * v^(-1)

False

In [9]:
with np.printoptions(precision=2):
    print(v @ w @ v)
    
with np.printoptions(precision=2):
    print((v @ np.diag(w)) @ np.linalg.inv(v))

[[ 4.    1.41 -1.07 -1.07  1.41]
 [ 0.    6.    0.    0.    6.  ]
 [ 0.    0.    6.    2.   -2.35]
 [ 0.    0.    0.    4.    2.35]
 [ 0.    0.    0.    0.    0.  ]]
[ 2.85e+17 -1.21e+17  1.20e+01  7.71e-16  6.98e-17]


In [10]:
A

array([[ 4.,  0.,  0.,  0.,  0.],
       [-4.,  6.,  0.,  0.,  0.],
       [ 0., -6.,  6.,  0.,  0.],
       [ 0.,  0., -6.,  4.,  0.],
       [ 0.,  0.,  0., -4.,  0.]])

In [12]:
np.allclose(np.matmul(A, v), np.matmul(v, w)) # A v = v w => A = v w (v^-1)

True

In [16]:
with np.printoptions(precision=2):
    print(v @ w @ v_inv) 

[[ 4.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-4.00e+00  6.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-1.76e+01  7.93e-01  6.00e+00  0.00e+00  0.00e+00]
 [ 6.92e+01  1.36e+00 -6.00e+00  4.00e+00  0.00e+00]
 [-5.20e+00  1.59e+00  3.52e-16 -4.00e+00  0.00e+00]]


In [26]:
v

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.74454718e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.93439169e-17,  3.48909435e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.67261242e-01,
         2.67261242e-01,  1.04672831e-16],
       [ 0.00000000e+00,  7.07106781e-01, -8.01783726e-01,
        -8.01783726e-01,  7.07106781e-01],
       [ 1.00000000e+00, -7.07106781e-01,  5.34522484e-01,
         5.34522484e-01, -7.07106781e-01]])

In [54]:
A

array([[ 4.,  0.,  0.,  0.,  0.],
       [-4.,  6.,  0.,  0.,  0.],
       [ 0., -6.,  6.,  0.,  0.],
       [ 0.,  0., -6.,  4.,  0.],
       [ 0.,  0.,  0., -4.,  0.]])

In [19]:
print(A.shape)
print(v.shape)
print(np.diag(w).shape)

(5, 5)
(5, 5)
(5, 5)


In [20]:
np.diag(w)

array([[0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 4.]])

In [21]:
v

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.74454718e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.93439169e-17,  3.48909435e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.67261242e-01,
         2.67261242e-01,  1.04672831e-16],
       [ 0.00000000e+00,  7.07106781e-01, -8.01783726e-01,
        -8.01783726e-01,  7.07106781e-01],
       [ 1.00000000e+00, -7.07106781e-01,  5.34522484e-01,
         5.34522484e-01, -7.07106781e-01]])