In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

In [14]:
N = 5
Rsi = 1
I_0 = 1

Q = np.zeros((N, N))

for i in range(N):
    if i != 0:
        Q[i, i - 1] = Rsi * i * (N - i)
    Q[i, i] = - np.sum(Q[i, :])

In [15]:
Q

array([[-0.,  0.,  0.,  0.,  0.],
       [ 4., -4.,  0.,  0.,  0.],
       [ 0.,  6., -6.,  0.,  0.],
       [ 0.,  0.,  6., -6.,  0.],
       [ 0.,  0.,  0.,  4., -4.]])

In [11]:
w, v = np.linalg.eig(Q)

print(w)
with np.printoptions(precision=2):
    print(v)

[4. 6. 6. 4.]
[[ 1.00e+00 -8.94e-01 -8.94e-01  1.00e+00]
 [ 0.00e+00  4.47e-01  4.47e-01  2.22e-16]
 [ 0.00e+00  0.00e+00  9.93e-17  7.40e-17]
 [ 0.00e+00  0.00e+00  0.00e+00  2.47e-17]]


In [12]:
v_inv = np.linalg.inv(v.copy())

In [13]:
np.allclose(Q @ v, v @ w)

False

In [2]:
N = 5 # total population
Rsi = 1

I_0 = 1
S_0 = 4

d1 = np.asarray([i * (N - i) for i in reversed(range(S_0 + 1))])
d2 = np.asarray([0] + [i * (N - i) for i in reversed(range(1, S_0 + 1))])
A = - (np.eye(S_0 + 1) * d1[:, np.newaxis]) + (np.eye(S_0 + 1, k=-1) * d2[:, np.newaxis])


In [3]:
A

array([[-4.,  0.,  0.,  0.,  0.],
       [ 4., -6.,  0.,  0.,  0.],
       [ 0.,  6., -6.,  0.,  0.],
       [ 0.,  0.,  6., -4.,  0.],
       [ 0.,  0.,  0.,  4.,  0.]])

In [5]:
w, v = np.linalg.eig(A)
v_inv = np.linalg.inv(v.copy())
w = np.diag(w.copy())

In [6]:
w

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., -4.,  0.,  0.,  0.],
       [ 0.,  0., -6.,  0.,  0.],
       [ 0.,  0.,  0., -6.,  0.],
       [ 0.,  0.,  0.,  0., -4.]])

In [7]:
v @ v_inv

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
v_inv

array([[-7.67176928e+00,  1.32238173e-01,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [ 5.73214651e+16,  5.61039052e-01,  4.24264069e+00,
         1.41421356e+00,  0.00000000e+00],
       [-3.37018536e+16,  1.68509268e+16,  3.74165739e+00,
         0.00000000e+00,  0.00000000e+00],
       [-3.37018536e+16,  1.68509268e+16, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00],
       [ 5.73214651e+16,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [9]:
np.allclose(v @ w @ v_inv, (v @ w) @ v_inv) # v * (w * v^(-1)) vs (v * w) * v^(-1)

True

In [9]:
with np.printoptions(precision=2):
    print(v @ w @ v)
    
with np.printoptions(precision=2):
    print((v @ np.diag(w)) @ np.linalg.inv(v))

[[ 4.    1.41 -1.07 -1.07  1.41]
 [ 0.    6.    0.    0.    6.  ]
 [ 0.    0.    6.    2.   -2.35]
 [ 0.    0.    0.    4.    2.35]
 [ 0.    0.    0.    0.    0.  ]]
[ 2.85e+17 -1.21e+17  1.20e+01  7.71e-16  6.98e-17]


In [13]:
np.allclose(A @ (v @ np.linalg.inv(v)), A) 

True

In [16]:
with np.printoptions(precision=2):
    print(v @ w @ v_inv) 

[[ 4.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-4.00e+00  6.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-1.76e+01  7.93e-01  6.00e+00  0.00e+00  0.00e+00]
 [ 6.92e+01  1.36e+00 -6.00e+00  4.00e+00  0.00e+00]
 [-5.20e+00  1.59e+00  3.52e-16 -4.00e+00  0.00e+00]]


In [26]:
v

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.74454718e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.93439169e-17,  3.48909435e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.67261242e-01,
         2.67261242e-01,  1.04672831e-16],
       [ 0.00000000e+00,  7.07106781e-01, -8.01783726e-01,
        -8.01783726e-01,  7.07106781e-01],
       [ 1.00000000e+00, -7.07106781e-01,  5.34522484e-01,
         5.34522484e-01, -7.07106781e-01]])

In [54]:
A

array([[ 4.,  0.,  0.,  0.,  0.],
       [-4.,  6.,  0.,  0.,  0.],
       [ 0., -6.,  6.,  0.,  0.],
       [ 0.,  0., -6.,  4.,  0.],
       [ 0.,  0.,  0., -4.,  0.]])

In [19]:
print(A.shape)
print(v.shape)
print(np.diag(w).shape)

(5, 5)
(5, 5)
(5, 5)


In [20]:
np.diag(w)

array([[0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 4.]])

In [21]:
v

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.74454718e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.93439169e-17,  3.48909435e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.67261242e-01,
         2.67261242e-01,  1.04672831e-16],
       [ 0.00000000e+00,  7.07106781e-01, -8.01783726e-01,
        -8.01783726e-01,  7.07106781e-01],
       [ 1.00000000e+00, -7.07106781e-01,  5.34522484e-01,
         5.34522484e-01, -7.07106781e-01]])